version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .var/www
    depends_on:
      - db


  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: trail
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
